[elasticsearch] user configurable Service sessionAffinity
elastic/helm-charts pull request #1134
Opened 2021-04-06 00:16 UTC by jstewart612

- [ x ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ x ] README.md updated with any new values or changes
- [ x ] Updated template tests in `${CHART}/tests/*.py` 
- [ not applicable requires no changes ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

2021-04-06 00:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-04-06 00:20 UTC, jstewart612 commented
I just signed the above agreement.  What needs to be done to force a recheck of this GHA status?

2021-04-12 13:39 UTC, jmlrt requested changes
Thanks for this PR, adding `sessionAffinity` is a gread addition, however can you recreate this PR for master branch instead of 6.8 branch?

Also chart version shouldn't be bumped.

2021-04-12 13:39 UTC, jmlrt commented on elasticsearch/Chart.yaml
> -version: 6.8.15
Chart versions are only bumped when we have a new release (https://github.com/elastic/helm-charts/blob/master/CONTRIBUTING.md#releases)

2021-08-10 14:25 UTC, closed without merging