fix: add labels at pod level, as well as deployment level
elastic/helm-charts pull request #1262
Opened 2021-06-23 17:37 UTC by drenze-athene

APM Server labels are applied at the deployment level only, not at the pod level. This does not align with the behavior of other Elastic helm charts in this collection. Additionally, it creates issues when using tools, which require specific labels to be applied to pods (i.e., validation tools, such as [OPA Gatekeeper](https://github.com/open-policy-agent/gatekeeper)).

Add labels defined under the `labels: {}` tag in `values.yml` to correct this issue.

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

2021-06-23 17:37 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-07-06 07:21 UTC, jmlrt commented
jenkins test this please

2021-07-06 08:17 UTC, jmlrt requested changes

2021-07-06 08:17 UTC, jmlrt commented on apm-server/templates/deployment.yaml
> +        chart: "{{ .Chart.Name }}"
```suggestion
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
```

to stay consistent with the other `chart` labels of APM Server chart

2021-09-21 16:45 UTC, jmlrt approved these changes
LGTM⛴

2021-09-21 16:45 UTC, jmlrt commented
jenkins test this please

2022-02-10 19:08 UTC, closed without merging

2022-02-10 19:33 UTC, mathewmeconry commented
@jmlrt @drenze-athene could we reopen the pull and merge it?
would really like to have this