[filebeat] using https to connect to elasticsearch
elastic/helm-charts pull request #1627
Opened 2022-03-21 16:30 UTC by framsouza

This PR will enable filebeat to connect into Elasticsearch via https

2022-03-21 16:39 UTC, framsouza commented
jenkins test this pipeline

2022-03-22 14:13 UTC, jmlrt commented
ok to test

2022-03-23 15:26 UTC, framsouza commented
jenkins test this pipeline please

2022-03-23 16:05 UTC, jmlrt requested changes

2022-03-23 16:05 UTC, jmlrt commented on filebeat/examples/upgrade/Makefile
> +FROM := 7.15.0 # registry file version 1 not supported error with previous version
```suggestion
FROM := 7.17.1	# upgrade from versions before 7.17.1 isn't compatible with 8.x
```

2022-03-23 16:05 UTC, jmlrt commented on filebeat/examples/upgrade/test/goss.yaml
> -      - "filebeat-8.1.0"
the body should stay, also will require :
```
username: '${ELASTICSEARCH_USERNAME}'
password: '${ELASTICSEARCH_PASSWORD}'
```

2022-03-23 16:22 UTC, jmlrt approved these changes
LGTM⛴

2022-03-23 16:58 UTC, framsouza commented
ok to test

2022-03-23 16:59 UTC, framsouza commented
jenkins test this pipeline please

2022-03-23 18:11 UTC, jmlrt commented
ok to test

2022-03-23 18:17 UTC, jmlrt commented
ok to test

2022-03-23 18:52 UTC, jmlrt commented
ok to test

2022-03-24 09:40 UTC, jmlrt approved these changes
LGTM⛴

2022-03-24 09:40 UTC, merged