Added ability to specify an existing Configmap for logstash pipelines
elastic/helm-charts pull request #450
Opened 2020-01-17 20:50 UTC by bpdunni

Added ability to specify an existing Configmap for logstash pipelines

Signed-off-by: Brian Dunnigan <bdun1013dev@gmail.com>

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

I would like to be able to specify an existing configmap that contains my logstash pipelines, instead of using the one created in the chart with the logstashPipeline value. This will allow me to have templated pipeline configmaps for deployment that I can point logstash installations to.

One issue that might arise is that if the existing configmap is changed, the logstash pods will need to be manually restarted. An approach that would work best would be the create a new configmap instead of editing the existing one, point the logstash release to the new configmap, then run a helm upgrade

The same can also be done for the configs (esConfig, kibanaConfig, etc) across the other charts and would be a useful feature. I will do those if this feature is accepted.

2020-01-17 20:50 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-01-20 10:38 UTC, jmlrt commented
jenkins test this please

2020-04-20 15:56 UTC, jmlrt commented
Hi @bpdunni, thank you for this PR and sorry for the delay.
This PR will need some time to review.

2020-07-10 06:44 UTC, qqshfox commented
Should also change this
```
          {{- range $path, $config := .Values.logstashPipeline }}
          - name: logstashpipeline
            mountPath: /usr/share/logstash/pipeline/{{ $path }}
            subPath: {{ $path }}
          {{- end -}}
```

to

```
{{- if .Values.existingPipelineConfigmap }}
- name: logstashpipeline
  mountPath: /usr/share/logstash/pipeline
{{- else }}
{{- range $path, $config := .Values.logstashPipeline }}
- name: logstashpipeline
  mountPath: /usr/share/logstash/pipeline/{{ $path }}
  subPath: {{ $path }}
{{- end -}}
{{- end -}}
```

to mount existing ConfigMaps to pod.

2020-10-12 06:49 UTC, jmlrt commented
still valid

2020-12-23 14:07 UTC, jmlrt commented
jenkins test this please

2020-12-23 15:43 UTC, jmlrt requested changes
Hi @bdun1013, thanks for this PR and sorry for the delay.

I finally took the time to think about this PR and review it, and I think this would make sense for Logstash chart.

As mentioned in https://github.com/elastic/helm-charts/pull/450#issuecomment-656512803, the `volumeMounts` change is missing.

Also I would prefer naming this new value `externalPipelineConfigmap`.

2020-12-23 15:43 UTC, jmlrt commented on logstash/tests/logstash_test.py
> +    assert r["statefulset"][name]["spec"]["template"]["metadata"]["annotations"] == None
This assertion doesn't test the pipeline from configmap feature and so should be removed

2020-12-23 15:43 UTC, jmlrt commented on logstash/README.md
> +| `existingPipelineConfigmap` | Allows you to specify an existing configmap containing pipeline files to add to `/usr/share/logstash/pipeline/`. If set `logstashPipeline` is ignored.
Maybe `externalPipelineConfigmap` would be more relevant.

2021-04-22 16:16 UTC, closed without merging