[release] bump 7.9 branch to 7.9.1-SNAPSHOT
elastic/helm-charts pull request #791
Opened 2020-08-18 22:25 UTC by ygel

This PR bump chart version and Docker images used to 7.9.1-SNAPSHOT to test 7.9.1 development version

See [New branching model](https://github.com/elastic/helm-charts/blob/master/BREAKING_CHANGES.md#new-branching-model) for more details.

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

2020-08-20 19:51 UTC, ygel commented
At least partial success this time:
![image](https://user-images.githubusercontent.com/51912343/90818760-a2d53200-e2f4-11ea-9eaa-44e43ec95066.png)

2020-08-25 16:33 UTC, jmlrt requested changes
Some lines that shouldn't be changed. The bumper script need to be reworked to prevent this.

2020-08-25 16:33 UTC, jmlrt commented on elasticsearch/examples/kubernetes-kind/README.md
> +fix it in Kind 0.7.9.1-SNAPSHOT
This line shouldn't be changed

2020-08-25 16:33 UTC, jmlrt commented on elasticsearch/examples/upgrade/README.md
> +- Upgrade from [7.9.1-SNAPSHOT][] version on K8S >=1.16 (Elasticsearch chart < 7.9.1-SNAPSHOT are
This line shouldn't be changed

2020-08-25 16:33 UTC, jmlrt commented on elasticsearch/examples/upgrade/README.md
> +[7.9.1-SNAPSHOT]: https://github.com/elastic/helm-charts/releases/tag/7.9.1-SNAPSHOT
This line shouldn't be changed

2020-08-25 16:41 UTC, jmlrt requested changes
Seems that I forgot to document that Elasticsearch API add `-SNAPSHOT` to the version while the other products don't do it 😭

2020-08-25 16:41 UTC, jmlrt commented on elasticsearch/examples/default/test/goss.yaml
> +      - '"number" : "7.9.1"'
```suggestion
      - '"number" : "7.9.1-SNAPSHOT"'
```

related to https://github.com/elastic/helm-charts/blob/ce7f0873a15fb8d80ec2cd3c74eb8547da171f88/elasticsearch/examples/default/test/goss.yaml#L18

2020-08-25 16:41 UTC, jmlrt commented on elasticsearch/examples/oss/test/goss.yaml
> +      - '"number" : "7.9.1"'
```suggestion
      - '"number" : "7.9.1-SNAPSHOT"'
```

related to https://github.com/elastic/helm-charts/blob/ce7f0873a15fb8d80ec2cd3c74eb8547da171f88/elasticsearch/examples/oss/test/goss.yaml#L14

2020-08-25 16:41 UTC, jmlrt commented on elasticsearch/examples/upgrade/test/goss.yaml
> +      - '"number" : "7.9.1"'
```suggestion
      - '"number" : "7.9.1-SNAPSHOT"'
```

related to https://github.com/elastic/helm-charts/blob/ce7f0873a15fb8d80ec2cd3c74eb8547da171f88/elasticsearch/examples/upgrade/test/goss.yaml#L14

2020-08-26 10:08 UTC, jmlrt commented
@ygel, you'll also need to merge `origin/7.9` on your branch to get https://github.com/elastic/helm-charts/pull/798 which is required to fix CI build.

2020-08-26 15:32 UTC, ygel commented
🎉 
```
10:15:04 Finished: SUCCESS
```

2020-08-26 15:36 UTC, jmlrt approved these changes
LGTM⛴

2020-08-26 15:37 UTC, jmlrt commented
We need to find a way to prevent or document the manual changes from 3d6ab1da3b150de53823277e48ab0abe7c4676d4

2020-08-26 15:37 UTC, merged

2020-08-26 15:37 UTC, ygel commented
please don't delete my 7.9 branch on the fork though :)