variable MaxUnavailbale updateStrategy
elastic/helm-charts pull request #809
Opened 2020-09-14 08:15 UTC by clemcvlcs

# Problem

Unable to set a custom value for the `MaxUnavalaible` for the `rollingUpdate` filebeat's update strategy.
This option should be available especially for filbert, because there is no need to have a MaxUnavailable set to 1 when there's one filebeat pod per node. 

# What I've done in PR

Add an `{{- if }}` statement to the `updateStrategy` regarding the `MaxUnavaillable` variable. If the variable is not set, the default value is et to **1** (current value set right now).

Chart version

filebeat 7.9.1

Tools versions

Helm version
Client: {Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}

2020-09-14 08:15 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-10-06 12:55 UTC, clemcvlcs commented
cla signed

2020-10-14 08:28 UTC, jmlrt commented
jenkins test this please

2020-10-14 08:36 UTC, jmlrt approved these changes
need to fix typo and update readme file. the rest lgtm 👍

2020-10-14 08:36 UTC, jmlrt commented on filebeat/values.yaml
> +MaxUnavalaible: 1
```suggestion
MaxUnavailable: 1
```

Can you also update the [README](https://github.com/elastic/helm-charts/blob/master/filebeat/README.md#configuration) with this new value?

2020-10-14 08:36 UTC, jmlrt requested changes
need to fix typo and update readme file. the rest lgtm 👍

2020-10-19 11:47 UTC, clemcvlcs commented
cla signed

2020-10-19 15:08 UTC, jmlrt commented
cla/check

2020-10-26 08:52 UTC, jmlrt commented
LGTM⛴

2020-10-26 08:53 UTC, jmlrt approved these changes
LGTM⛴

2020-10-27 15:00 UTC, jmlrt commented
jenkins test this please

2020-10-27 15:51 UTC, jmlrt requested changes
Oops, `MaxUnavailable` value is still missing in the [README value table](https://github.com/elastic/helm-charts/tree/master/filebeat#configuration). Can you add it please?

2021-01-28 09:01 UTC, jmlrt commented
@clemcvlcs, I merged master on your branch and updated it in regard of #964 which is adding Filebeat deployment, also updated README and tests.

I can't push on your branch so my changes are https://github.com/elastic/helm-charts/commit/2ce2c796323e3fe88388ea4b213049c155c4e6a3, https://github.com/elastic/helm-charts/commit/873fd835873050711dc60806c5553f45b7e32de6 and https://github.com/elastic/helm-charts/commit/702985288287f4fa802dc85a702e412361cb70df.

Are you interested to update your PR with these changes so we can merge it?

2021-01-28 09:45 UTC, jmlrt commented
jenkins test this please

2021-01-28 10:56 UTC, jmlrt commented
Ooops forgot to format python tests https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/784/label=docker&&virtual&&ubuntu-18.04/console 🤦

Can you run `black filebeat/tests`?

The other error (https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/1163/CHART=filebeat,label=docker&&virtual/console) is strange and I don't have it locally. I'll rerun the CI tests after formatting.

2021-01-28 11:12 UTC, jmlrt commented
jenkins test this please

2021-01-28 11:40 UTC, jmlrt approved these changes
LGTM⛴ Black tests are failing on some part of the code which haven't been changed  🤷‍♂️. I'll fix it in another PR if required.

2021-01-28 11:41 UTC, merged