Support for Deployment Kubernetes resource
elastic/helm-charts pull request #822
Opened 2020-09-24 10:00 UTC by operatorequals

This commit indtroduces the feature of deploying a Kubernetes deployment
instead of a Daemonset using Filebeat, using a `values.yaml` syntax
as below:

`values.yaml`
---
```yaml
[...]
deploymentType: [daemonset|deployment]
[...]
```

Specifically, this is used for creation of Filebeat instances not
bound to each Worker, conducting non-Worker-related work, such as
collection of AWS CloudTrail logs as described in [1].

[1]:https://github.com/elastic/helm-charts/issues/821

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

2020-09-24 10:00 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-25 11:47 UTC, operatorequals commented
Hello people!
I signed the CLA, is there something that I need to do for the PR to get tested?

Thanks!

2020-10-02 10:38 UTC, jmlrt requested changes
Hi @operatorequals, thanks for submitting this PR.

Metricbeat chart is already managing both daemonset and deployment resources using `daemonset.enable` and `deployment.enable` values.

For consistency reason between Elastic charts, I would prefer having the same behavior in Filebeat chart if we had the feature to manage Filebeat deployment resources.

Can you refactor your PR according to Metricbeat chart code?

2020-10-02 10:55 UTC, operatorequals commented
> Hi @operatorequals, thanks for submitting this PR.

> Can you refactor your PR according to Metricbeat chart code?

Absolutely!

2020-10-21 10:58 UTC, operatorequals commented
I did refactor the PR in a way that accepts defaults from the YAML root key, and also get overriden by `deployment/daemonset` keys.

2020-11-16 14:41 UTC, jmlrt commented
jenkins test this please

2020-11-16 14:42 UTC, jmlrt requested changes
Thanks for this great work 👍

2020-11-16 14:42 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +  name: '{{ template "filebeat.fullname" . }}'
these single quotes make it harder to compare daemonset and deployment templates using some `diff daemonset.yaml deployment.yaml` or editor diff options. 

Is there any specific reason for adding them here?

Could you stick to `daemonset.yml` "format" so a diff between the 2 templates should print only the differences?

2020-11-16 14:42 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +  {{- if .Values.deployment.annotations}}
if we add annotations here, we should add them also in daemonset template for consistency

2020-11-16 14:42 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +    release: '{{ .Release.Name }}'
Can you add also `.Values.labels` here for consistency?

2020-11-16 14:42 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +      heritage: '{{ .Release.Service }}'
Can you remove `heritage` label from selector? We removed it everywhere because it can be cause of trouble when migrating from Helm 2 to Helm 3

2020-11-16 14:42 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +        {{- if or  .Values.filebeatConfig .Values.deployment.filebeatConfig }}
👍  this should be updated the same way in daemonset template

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> +  enabled: true
The deployment should be disabled by default

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> +        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
IMO this configuration isn't relevant for a Filebeat deployment. We should find some default configuration which match a standard and relevant use case or leave it empty.

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> -# Allows you to add any config files in /usr/share/filebeat
Can you re-add all these removed key in a deprecated section with empty value like in the metricbeat chart:

https://github.com/elastic/helm-charts/blob/58bdd96312a08cf3e933ffa9afb3c7988c27dd80/metricbeat/values.yaml#L275-L289

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> +  annotations: {}
`labels: {}` is missing here

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
>  hostNetworking: false
`hostNetworking` should be par of the `daemonset` key

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> +      memory: "200Mi"
`tolerations` is missing here.

2020-11-16 14:42 UTC, jmlrt commented on filebeat/values.yaml
> +  annotations: {}
`labels: {}` is missing here

2020-11-16 14:42 UTC, jmlrt commented on filebeat/README.md
> +| `deploymentType`         | Whether Filebeat will be deployed as `DaemonSet` running on all Worker nodes (default) or `Deployment`
This is not used anymore

2020-11-16 14:42 UTC, jmlrt commented on filebeat/README.md
> +| `deploymentType`         | Whether Filebeat will be deployed as `DaemonSet` running on all Worker nodes (default) or `Deployment`
All new `daemonset` and deployment sub-values should be documented here.

2020-11-19 17:03 UTC, operatorequals commented
On it!

2020-12-02 16:40 UTC, jmlrt commented
jenkins test this please

2020-12-02 17:40 UTC, operatorequals commented
As of [Jenkins](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/1067/CHART=filebeat,label=docker&&virtual/console) the `tolerations` defaults is failing:
```python
16:42:29 >       assert "tolerations" not in r["daemonset"][name]["spec"]["template"]["spec"]
16:42:29 E       AssertionError: assert 'tolerations' not in {'affinity': {}, 'containers': [{'args': ['-e', '-E', 'http.enabled=true'], 'env': [{'name': 'POD_NAMESPACE', 'valueFr...astic.co/beats/filebeat:8.0.0-SNAPSHOT', ...}], 'nodeSelector': {}, 'serviceAccountName': 'release-name-filebeat', ...}
16:42:29 
```

The line should be replaced with:
```python
    assert (
        r["daemonset"][name]["spec"]["template"]["spec"]["tolerations"]
        == []
    )
```
(taken from [Metricbeat](https://github.com/elastic/helm-charts/blob/c0af9b46bdaeb2722a3713f12d073732e945014a/metricbeat/tests/metricbeat_test.py#L41)).

Yet, I lost access to the fork due to an accident and I cannot push another commit:
<img width="699" alt="εικόνα" src="https://user-images.githubusercontent.com/6146328/100910070-5f7a8a00-34c5-11eb-95fd-8e11572ed9b7.png">

After that, the tests will have lower coverage but they will pass.

2020-12-02 17:44 UTC, jmlrt requested changes
Ensuring that everything is fin for this PR is a very tedious work so many thanks for it 👍

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
>      {{- range $key, $value := .Values.labels }}
```suggestion
    {{- if .Values.daemonset.labels }}
    {{- range $key, $value := .Values.daemonset.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- else }}
    {{- range $key, $value := .Values.labels }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
>      {{- end }}
```suggestion
    {{- end }}
    {{- end }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
> +  {{- if .Values.deployment.annotations }}
```suggestion
  {{- if .Values.daemonset.annotations }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
> +    {{- range $key, $value := .Values.deployment.annotations }}
```suggestion
    {{- range $key, $value := .Values.daemonset.annotations }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
>          {{ $key }}: {{ $value | quote }}
The `.Values.labels` block should be:
```
        {{- if .Values.daemonset.labels }}
        {{- range $key, $value := .Values.daemonset.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- else }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
>        {{- if .Values.hostNetworking }}
```suggestion
      {{- if .Values.daemonset.hostNetworking }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
`heritage` labels should stay here and be removed from `selector`

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +    {{- end }}
```suggestion
    {{- if .Values.deployment.labels }}
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- else }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +      release: {{ .Release.Name | quote }}
```suggestion
      release: {{ .Release.Name | quote }}
      {{- if .Values.deployment.labels }}
      {{- range $key, $value := .Values.deployment.labels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- else }}
      {{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +  replicas: {{ .Values.replicas }}
this value seems missing in the value file and readme

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/deployment.yaml
> +        heritage: '{{ .Release.Service }}'
can you remove `heritage` label here also?

2020-12-02 17:44 UTC, jmlrt commented on filebeat/templates/daemonset.yaml
>            {{- if .subPath }}
```
        {{- range $path, $config := .Values.filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
```

block below should be replaced by

```
        {{- range $path, $config := .Values.filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.daemonset.filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
```

2020-12-02 17:44 UTC, jmlrt commented on filebeat/README.md
> -| `hostNetworking`            | Use host networking in the DaemonSet so that hostname is reported correctly
this should be moved to deprecated

2020-12-02 17:44 UTC, jmlrt commented on filebeat/README.md
> -| `dnsConfig`                 | Configurable [dnsConfig][]
this is missing (should be moved to daemonset and deprecated values)

2020-12-02 17:46 UTC, jmlrt commented
> After that, the tests will have lower coverage but they will pass.

Yep tests will also need some refactoring pretty similar to what I did for `metricbeat_test.py` in https://github.com/elastic/helm-charts/pull/572/files?file-filters%5B%5D=.py

2020-12-02 17:47 UTC, operatorequals commented on filebeat/templates/daemonset.yaml
> +  annotations:  # comment 2
Nothing. They are just comments. Can you delete them or open suggestions, as I can no longer push (my bad)?

2020-12-05 23:19 UTC, operatorequals commented
Hello @jmlrt !
This PR is no longer usable because I lost control of the base branch (by deleting my fork).
[This PR](https://github.com/elastic/helm-charts/pull/964/) does contain all the commits from the current one, plus the suggested fixes to finalize Filebeat as deployment. I am closing this one and let's continue our work here:
https://github.com/elastic/helm-charts/pull/964

2020-12-07 09:01 UTC, closed without merging