[logstash] Add support to use pattern files
elastic/helm-charts pull request #883
Opened 2020-11-02 08:26 UTC by tuananhnguyen-ct

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fixes https://github.com/elastic/helm-charts/issues/685, as we don't want to manage the pattern via a configmap externally.

To use the pattern, add `patterns_dir => "/usr/share/logstash/patterns"` to your filter.

2020-11-02 08:27 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-11-11 04:01 UTC, tuananhnguyen-ct commented
@jmlrt can I have a review here please? Thank you.

2020-11-18 11:06 UTC, jmlrt commented
Hi @tuananhnguyen-ct,
Thanks for opening this PR.
We'll try to review it soon. Please be patient.

2020-11-18 11:06 UTC, jmlrt commented
LGTM⛴

2020-11-18 11:06 UTC, jmlrt commented
jenkins test this please

2020-12-10 07:17 UTC, ebuildy submitted a review, later dismissed

2020-12-14 10:04 UTC, tuananhnguyen-ct commented
@jmlrt please review, the test has passed. Thanks a lot.

2021-02-03 13:35 UTC, jmlrt requested changes
Hi @tuananhnguyen-ct, this looks mostly good outside of the copy/paste error in the README.
I'll also try to get someone else with better knowledge of Logstash pattern files than me.

2021-02-03 13:35 UTC, jmlrt commented on logstash/README.md
> +| `logstashPipeline`        | Allows you to add any pattern files in `logstashPatternDir` | `{}` |
```suggestion
| `logstashPattern`        | Allows you to add any pattern files in `logstashPatternDir` | `{}` |
```

2021-02-04 10:17 UTC, jmlrt approved these changes
LGTM⛴

2021-02-04 10:18 UTC, jmlrt commented
jenkins test this please

2021-02-05 09:32 UTC, jmlrt commented
jenkins test this please

2021-02-05 10:21 UTC, merged