Add warning comment placeholder (7.9 branch)
elastic/helm-charts pull request #884
Opened 2020-11-03 12:23 UTC by nkammah

The development warning comment will help with the automation (especially to add the warning back). This PR is to be backported against `6.8`, _main branch_, `7.x`.

2020-11-04 09:05 UTC, jmlrt approved these changes
LGTM⛴

2020-11-04 09:06 UTC, jmlrt commented
> I will backport the PR against `6.8`, _main branch_, `7.x` once this one is reviewed and merged

FYI, the expected workflow is to create the PR against _main branch_, then to backport it on `7.x`, `7.9`, and `6.8`

2020-11-04 09:13 UTC, jmlrt requested changes
Markdown preview is uncorrect:

<img width="1168" alt="Screenshot 2020-11-04 at 10 12 04" src="https://user-images.githubusercontent.com/8582351/98091875-46f75f80-1e86-11eb-9431-30d7c0050442.png">

2020-11-04 09:19 UTC, jmlrt commented on apm-server/README.md
> +<!-- development warning -->**Warning**: This branch is used for development, please use the latest [7.x][] release for released version.
```
<!-- development warning placeholder -->
**Warning**: This branch is used for development, please use the latest [7.x][] release for released version.
```

I have 2 suggestions:
- maybe add "placeholder" in the markdown comment to make it more explicit what it is, especially when the warning is removed in released version
- maybe move placeholder comment and warning statements on different lines to fix the markdown format issue

2020-11-05 11:17 UTC, jmlrt approved these changes
LGTM⛴

2020-11-05 11:36 UTC, nkammah commented
jenkins test this please

2020-11-05 12:08 UTC, merged