Fix - Metricbeat default values - output module config
elastic/helm-charts pull request #960
Opened 2020-12-01 17:34 UTC by njgibbon

I believe there is a typo in the current configuration.

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [x] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

2020-12-01 17:34 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-12-07 14:28 UTC, jmlrt requested changes
Hi @njgibbon,
This is not a typo but the expected syntax so that if `ELASTICSEARCH_HOSTS` variable is defined, `hosts` will match it, otherwise, `hosts` will default to `elasticsearch-master:9200`.

2020-12-07 15:35 UTC, nickgibbon-nationwide commented
Ah ok I see. There you go \/. I never knew 👍 

https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion

Will close this.

2020-12-07 15:38 UTC, njgibbon commented
Ah ok I see. I never knew 👍

https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion

Will close this.

2020-12-07 15:38 UTC, closed without merging