[metricbeats][filebeats] Ran doctoc to update FAQ which updated sub-folders as well.
elastic/helm-charts pull request #999
Opened 2020-12-23 16:50 UTC by kwsorensen

- [ x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

I just wanted to see my FAQ updated in the README's TOC

2020-12-23 16:50 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-12-23 18:10 UTC, kwsorensen commented
Ran the `docker run --rm -it -v $(pwd):/usr/src jorgeandrada/doctoc` according to the readme to update the TOC. To represent my previous addition to the READMEs

2020-12-28 15:35 UTC, kwsorensen commented
Follow up to https://github.com/elastic/helm-charts/pull/997.

2021-01-04 11:17 UTC, jmlrt requested changes
Hi @kwsorensen,
Thanks for this PR.

- Can you rebase your branch on master?
- Also README files in examples directory shouldn't be updated with TOC. Can you remove this change?
- Finally It seems tha `Configuration` header has been dropped from Filebeat README by mistake in https://github.com/elastic/helm-charts/pull/964/files#diff-9148fe0a90c1405cb044332ee4f53092291d5c4c6a24d3d7d999d8fa056ab5e1L89. It could be great if you can fix it in this PR. (I can fix it in another PR otherwise).

2021-01-04 11:17 UTC, jmlrt commented on filebeat/README.md
> -- [Configuration](#configuration)
Tghis shouldn't be removed from the TOC. It seems this header was removed by mistake in a previous PR.

2021-01-04 11:17 UTC, jmlrt commented on filebeat/README.md
> +### How do I get multiple beats agents working with hostNetworking enabled?
This shouldn't be seen as a new change as #997 has been merged. Can you try to rebase master on your branch?

2021-01-04 11:17 UTC, jmlrt commented on metricbeat/README.md
> +### How do I get multiple beats agents working with hostNetworking enabled?
This shouldn't be seen as a new change as #997 has been merged. Can you try to rebase master on your branch?

2021-02-14 18:39 UTC, closed without merging